services:
  php:
    image: webdevops/php:8.1-alpine
    container_name: bitrix-php
    volumes:
      - ./bitrix:/var/www/bitrix
      - ./php/php.ini:/opt/docker/etc/php/php.ini
    ports:
      - '9000:9000'

  nginx:
    build: ./nginx
    container_name: bitrix-nginx
    ports:
      - 80:80
    volumes:
      - ./bitrix:/var/www/bitrix
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/conf/upstream.conf:/etc/nginx/conf.d/upstream.conf
    command: nginx

  db:
    image: mysql:5.7
    container_name: bitrix-db
    environment:
      MYSQL_DATABASE: bitrix
      MYSQL_USER: bitrix
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: 123
    volumes:
      - ./mysql/dump:/dump
      - ./mysql/data:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf

  adminer:
    image: adminer
    container_name: bitrix-adminer
    ports:
      - 8080:8080
    